language: python
sudo: required
dist: trusty
env:
  - TOXENV=py27 TEST=functional
  - TOXENV=py35 TEST=functional
  - TOXENV=style
  - TOXENV=docs
before_install:
  # Install tor and chutney if doing functional tests
  - if [[ $TEST == 'functional' ]]; then ./test/scripts/install-tor.sh; fi
  - if [[ $TEST == 'functional' ]]; then source test/scripts/install-chutney.sh; fi
install:
  - pip install tox
script:
  - tox
